import { GetServerSideProps } from "next";
import Head from "next/head";
import { initializeApollo } from "../lib/client";
import styles from "../styles/Home.module.css";
import { gql, useQuery } from "@apollo/client";
import CompanyList from "../components/company-list";
import { CompanySpecialities } from "../backend/types";

export const GET_ALL_COMPANIES_QUERY = gql`
  query GET_ALL_COMPANIES_QUERY($input: GetAllCompaniesInput!) {
    companies: getAllCompanies(input: $input) {
      id
      name
      city
      logo
      specialities
    }
  }
`;

interface CompaniesQuery {
  companies: {
    id: number;
    name: string;
    city: string;
    logo: string;
    specialities: CompanySpecialities;
  }[];
}

export default function Home() {
  const result = useQuery<CompaniesQuery>(GET_ALL_COMPANIES_QUERY, {
    variables: { input: {} },
  });
  const data = result.data?.companies;

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        {result.loading && !data ? (
          <p>Loading ...</p>
        ) : result.error ? (
          <p>An error occured ...</p>
        ) : data && data.length > 0 ? (
          <CompanyList companies={data} />
        ) : (
          <p> You donn't have companies yet!</p>
        )}
      </main>
    </div>
  );
}

export const getServerSideProps: GetServerSideProps = async (context) => {
  //TODO: Add check for '?search=TEXT&filter=TEXT' here

  const apolloClient = initializeApollo();
  await apolloClient.query({
    query: GET_ALL_COMPANIES_QUERY,
    variables: {
      input: {},
    },
  });

  return { props: { initialApolloState: apolloClient.cache.extract() } };
};
